name: upload

on: 
  push:
    branches:
      'main'

jobs:

  upload:
    environment: basic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          mkdir -p ~/.ssh/
          echo $KEY > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa

          ls -l ~/.ssh/id_ecdsa

        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          cd $GITHUB_WORKSPACE/src
          ./build

          scp -rv $GITHUB_WORKSPACE/docroot $REMOTE:$BASE


env:
  REMOTE: jrootham@jrootham.ca
  BASE: /var/www/vhosts/jrootham.ca/mchc.jrootham.ca



      
